name: kalpatru_services
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path_provider: ^2.1.2
  path: any
  firebase_core: ^2.31.0
  firebase_auth: ^4.17.4
  audioplayers: ^6.5.0
  firebase_messaging: ^14.7.5
  flutter_local_notifications: ^19.3.0
  http: ^1.4.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/kalpatru_bg.jpeg
    - assets/qr.jpeg
    - assets/ringtone.mpeg

